[versions]
android-gradle-plugin = "7.0.4"
androidx-core = "1.7.0"
androidx-hilt = "1.0.0"
androidx-lifecycle = "2.4.0"
androidx-room = "2.4.0"
androidx-viewpager2 = "1.0.0"
androidx-work = "2.7.1"
dagger = "2.40.5"
eventbus = "3.3.1"
facebook-flipper = "0.125.0"
firebase-crashlytics = "18.2.6"
firebase-perf = "20.0.4"
godtoolsMpp = "0.4.1-SNAPSHOT"
google-auto-value = "1.9"
gtoSupport = "3.11.0-SNAPSHOT"
jacoco = "0.8.7"
kotlin = "1.6.10"
kotlinCoroutines = "1.5.2"
materialComponents = "1.4.0"
okhttp3 = "4.9.3"
retrofit2 = "2.9.0"
scarlet = "0.1.12"
splitties = "3.0.0"

[libraries]
advrecyclerview = "com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:1.0.0"
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
androidx-annotation = "androidx.annotation:annotation:1.3.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.0"
androidx-arch-core-testing = "androidx.arch.core:core-testing:2.1.0"
androidx-browser = "androidx.browser:browser:1.4.0"
androidx-cardview = "androidx.cardview:cardview:1.0.0"
androidx-collection-ktx = "androidx.collection:collection-ktx:1.2.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.2"
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-databinding-compiler = { module = "androidx.databinding:databinding-compiler", version.ref = "android-gradle-plugin" }
androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.4.0"
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-testing = { module = "androidx.lifecycle:lifecycle-runtime-testing", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.1"
androidx-room = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
androidx-test-junit = "androidx.test.ext:junit:1.1.3"
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-work = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-work-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
appsflyer = "com.appsflyer:af-android-sdk:6.5.0"
circleindicator = "me.relex:circleindicator:2.1.6"
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
eventbus-annotationProcessor = { module = "org.greenrobot:eventbus-annotation-processor", version.ref = "eventbus" }
facebook = "com.facebook.android:facebook-core:12.2.0"
facebook-flipper = { module = "com.facebook.flipper:flipper", version.ref = "facebook-flipper" }
facebook-flipper-plugins-network = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "facebook-flipper" }
facebook-soloader = "com.facebook.soloader:soloader:0.10.3"
firebase-appdistribution-gradlePlugin = "com.google.firebase:firebase-appdistribution-gradle:2.2.0"
firebase-core = "com.google.firebase:firebase-core:20.0.1"
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
firebase-crashlytics-gradlePlugin = "com.google.firebase:firebase-crashlytics-gradle:2.8.1"
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk", version.ref = "firebase-crashlytics" }
firebase-inappmessaging = "com.google.firebase:firebase-inappmessaging-display:20.1.1"
firebase-messaging = "com.google.firebase:firebase-messaging:23.0.0"
firebase-perf = { module = "com.google.firebase:firebase-perf", version.ref = "firebase-perf" }
firebase-perf-gradlePlugin = "com.google.firebase:perf-plugin:1.4.0"
firebase-perf-ktx = { module = "com.google.firebase:firebase-perf-ktx", version.ref = "firebase-perf" }
godtoolsMpp-parser = { module = "org.cru.godtools.kotlin:parser", version.ref = "godtoolsMpp" }
google-auto-value = { module = "com.google.auto.value:auto-value", version.ref = "google-auto-value" }
google-auto-value-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "google-auto-value" }
google-services-gradlePlugin = "com.google.gms:google-services:4.3.10"
gtoSupport-androidx-databinding = { module = "org.ccci.gto.android:gto-support-androidx-databinding", version.ref = "gtoSupport" }
gtoSupport-androidx-drawerlayout = { module = "org.ccci.gto.android:gto-support-androidx-drawerlayout", version.ref = "gtoSupport" }
gtoSupport-androidx-fragment = { module = "org.ccci.gto.android:gto-support-androidx-fragment", version.ref = "gtoSupport" }
gtoSupport-androidx-lifecycle = { module = "org.ccci.gto.android:gto-support-androidx-lifecycle", version.ref = "gtoSupport" }
gtoSupport-androidx-room = { module = "org.ccci.gto.android:gto-support-androidx-room", version.ref = "gtoSupport" }
gtoSupport-androidx-viewpager2 = { module = "org.ccci.gto.android:gto-support-androidx-viewpager2", version.ref = "gtoSupport" }
gtoSupport-androidx-work = { module = "org.ccci.gto.android:gto-support-androidx-work", version.ref = "gtoSupport" }
gtoSupport-animation = { module = "org.ccci.gto.android:gto-support-animation", version.ref = "gtoSupport" }
gtoSupport-appcompat = { module = "org.ccci.gto.android:gto-support-appcompat", version.ref = "gtoSupport" }
gtoSupport-base = { module = "org.ccci.gto.android:gto-support-base", version.ref = "gtoSupport" }
gtoSupport-compat = { module = "org.ccci.gto.android:gto-support-compat", version.ref = "gtoSupport" }
gtoSupport-core = { module = "org.ccci.gto.android:gto-support-core", version.ref = "gtoSupport" }
gtoSupport-dagger = { module = "org.ccci.gto.android:gto-support-dagger", version.ref = "gtoSupport" }
gtoSupport-db = { module = "org.ccci.gto.android:gto-support-db", version.ref = "gtoSupport" }
gtoSupport-db-coroutines = { module = "org.ccci.gto.android:gto-support-db-coroutines", version.ref = "gtoSupport" }
gtoSupport-db-livedata = { module = "org.ccci.gto.android:gto-support-db-livedata", version.ref = "gtoSupport" }
gtoSupport-eventbus = { module = "org.ccci.gto.android:gto-support-eventbus", version.ref = "gtoSupport" }
gtoSupport-facebook-flipper = { module = "org.ccci.gto.android:gto-support-facebook-flipper", version.ref = "gtoSupport" }
gtoSupport-firebase-crashlytics = { module = "org.ccci.gto.android:gto-support-firebase-crashlytics", version.ref = "gtoSupport" }
gtoSupport-jsonapi = { module = "org.ccci.gto.android:gto-support-jsonapi", version.ref = "gtoSupport" }
gtoSupport-jsonapi-retrofit2 = { module = "org.ccci.gto.android:gto-support-jsonapi-retrofit2", version.ref = "gtoSupport" }
gtoSupport-jsonapi-scarlet = { module = "org.ccci.gto.android:gto-support-jsonapi-scarlet", version.ref = "gtoSupport" }
gtoSupport-kotlin-coroutines = { module = "org.ccci.gto.android:gto-support-kotlin-coroutines", version.ref = "gtoSupport" }
gtoSupport-leakcanary = { module = "org.ccci.gto.android:gto-support-leakcanary2", version.ref = "gtoSupport" }
gtoSupport-lottie = { module = "org.ccci.gto.android:gto-support-lottie", version.ref = "gtoSupport" }
gtoSupport-materialComponents = { module = "org.ccci.gto.android:gto-support-material-components", version.ref = "gtoSupport" }
gtoSupport-napier = { module = "org.ccci.gto.android:gto-support-napier", version.ref = "gtoSupport" }
gtoSupport-okhttp3 = { module = "org.ccci.gto.android:gto-support-okhttp3", version.ref = "gtoSupport" }
gtoSupport-okta = { module = "org.ccci.gto.android:gto-support-okta", version.ref = "gtoSupport" }
gtoSupport-picasso = { module = "org.ccci.gto.android:gto-support-picasso", version.ref = "gtoSupport" }
gtoSupport-recyclerview = { module = "org.ccci.gto.android:gto-support-recyclerview", version.ref = "gtoSupport" }
gtoSupport-recyclerview-advrecyclerview = { module = "org.ccci.gto.android:gto-support-recyclerview-advrecyclerview", version.ref = "gtoSupport" }
gtoSupport-retrofit2 = { module = "org.ccci.gto.android:gto-support-retrofit2", version.ref = "gtoSupport" }
gtoSupport-scarlet = { module = "org.ccci.gto.android:gto-support-scarlet", version.ref = "gtoSupport" }
gtoSupport-scarlet-actioncable = { module = "org.ccci.gto.android:gto-support-scarlet-actioncable", version.ref = "gtoSupport" }
gtoSupport-snowplow = { module = "org.ccci.gto.android:gto-support-snowplow", version.ref = "gtoSupport" }
gtoSupport-sync = { module = "org.ccci.gto.android:gto-support-sync", version.ref = "gtoSupport" }
gtoSupport-testing-dagger = { module = "org.ccci.gto.android.testing:gto-support-dagger", version.ref = "gtoSupport" }
gtoSupport-testing-okta = { module = "org.ccci.gto.android.testing:gto-support-okta", version.ref = "gtoSupport" }
gtoSupport-testing-picasso = { module = "org.ccci.gto.android.testing:gto-support-picasso", version.ref = "gtoSupport" }
gtoSupport-testing-timber = { module = "org.ccci.gto.android.testing:gto-support-timber", version.ref = "gtoSupport" }
gtoSupport-util = { module = "org.ccci.gto.android:gto-support-util", version.ref = "gtoSupport" }
gtoSupport-viewpager = { module = "org.ccci.gto.android:gto-support-viewpager", version.ref = "gtoSupport" }
guava = { module = "com.google.guava:guava", version = "31.0.1-android" }
hamcrest = "org.hamcrest:hamcrest:2.2"
hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-gradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
json = "org.json:json:20211205"
jsoup = "org.jsoup:jsoup:1.14.3"
junit = "junit:junit:4.13.2"
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
leakcanary = "com.squareup.leakcanary:leakcanary-android:2.7"
lottie = "com.airbnb.android:lottie:4.2.2"
materialBanner = "com.sergivonavi:materialbanner:1.2.0"
materialComponents = { module = "com.google.android.material:material", version.ref = "materialComponents" }
mockito = "org.mockito:mockito-inline:4.1.0"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:4.0.0"
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okta = "com.okta.android:okta-oidc-android:1.2.1"
picasso = "com.squareup.picasso:picasso:2.8"
picasso-transformations = "jp.wasabeef:picasso-transformations:2.4.0"
play-billing = "com.android.billingclient:billing:4.0.0"
play-core = "com.google.android.play:core:1.10.2"
play-installreferrer = "com.android.installreferrer:installreferrer:2.2"
play-instantapps = "com.google.android.instantapps:instantapps:1.1.0"
play-tagmanager = "com.google.android.gms:play-services-tagmanager:18.0.0"
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit2-converters-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit2" }
robolectric = "org.robolectric:robolectric:4.7.3"
rtlViewpager = "com.duolingo.open:rtl-viewpager:2.0.0"
scarlet = { module = "com.tinder.scarlet:scarlet", version.ref = "scarlet" }
scarlet-adapters-stream-coroutines = { module = "com.tinder.scarlet:stream-adapter-coroutines", version.ref = "scarlet" }
scarlet-lifecycle-android = { module = "com.tinder.scarlet:lifecycle-android", version.ref = "scarlet" }
scarlet-websockets-okhttp = { module = "com.tinder.scarlet:websocket-okhttp", version.ref = "scarlet" }
snowplow = "com.snowplowanalytics:snowplow-android-tracker:3.0.0"
splitties-bitflags = { module = "com.louiscad.splitties:splitties-bitflags", version.ref = "splitties" }
splitties-fragmentargs = { module = "com.louiscad.splitties:splitties-fragmentargs", version.ref = "splitties" }
splitties-intents = { module = "com.louiscad.splitties:splitties-intents", version.ref = "splitties" }
taptargetview = "com.getkeepsafe.taptargetview:taptargetview:1.13.3"
timber = "com.jakewharton.timber:timber:5.0.1"
tinder-statemachine = "com.tinder.statemachine:statemachine:0.2.0"
weakdelegate = "com.github.Karumi:WeakDelegate:1.0.1"
youtubePlayer = "com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5"

[plugins]
grgit = { id = "org.ajoberstar.grgit", version = "4.1.1" }
junitJacoco = { id = "com.vanniktech.android.junit.jacoco", version = "0.16.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "10.2.0" }
